### ISSUE TITLE
missing Matbuf

### ISSUE THREAD

**Issue by sangelxyz** [frozenlib/lgbm-rs#1]
Hi, great work on the library. 

I had some issues building using
[dependencies]
lgbm = "0.0.1"

changing to

lgbm = {git = "https://github.com/frozenlib/lgbm-rs"}

seemed to fix the issue when building.

**Comment by frozenlib** [comment]
Thank you for your report.

This is due to an incompatibility change made after the release of version 0.0.1.

It is confusing and I will release a new version soon.
