### ISSUE TITLE
Unable to use the crate in macOS M2 chip

### ISSUE THREAD

**Issue by gagansingh894** [frozenlib/lgbm-rs#2]
I have installed the lightgbm package as instructed using homebrew. However when i try to run my program, I get the error

```
ld: library '_lightgbm' not found
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My code:
```
    #[test]
    fn successfully_load_lightgbm_regressor_model() {
        let path = "model_artefacts/lgbm_reg.txt";
        let model = LightGBM::load(path);

        // assert the result is ok
        assert!(model.is_ok())
    }
```

Output from brew info

```
==> lightgbm: stable 4.3.0 (bottled)
Fast, distributed, high performance gradient boosting framework
https://github.com/microsoft/LightGBM
Installed
/opt/homebrew/Cellar/lightgbm/4.3.0 (112 files, 21MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-05-19 at 13:30:34
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/l/lightgbm.rb
License: MIT
==> Dependencies
Build: cmake ✔
Required: libomp ✘
==> Analytics
install: 399 (30 days), 1,203 (90 days), 5,015 (365 days)
install-on-request: 399 (30 days), 1,203 (90 days), 5,015 (365 days)
build-error: 0 (30 days)
```

**Comment by gagansingh894** [comment]
Closing the issue as I was able to fix it. The issue was I did not had usr/local/lib folder but with the following steps I was able to resolve the issue

- cd into `/usr/local` from home
`cd ../../usr/local`

- create a new dir
`sudo mkdir usr/lib
`
- create symbolic link to library
`sudo ln -s /opt/homebrew/Cellar/lightgbm/4.3.0/lib/lib_lightgbm.dylib .
`

**Comment by frozenlib** [comment]
Thanks for your report. With the information you provided, I was able to update the `build.rs` and requirements, and now I can build with the macOS-14-arm64 image of GitHub Actions.

However, I don't have the actual device at hand and have not been able to test it on the actual device, so if there are any more problems, please create an issue or submit a PR.
