### ISSUE TITLE
How would we use monotone_constraints ?

### ISSUE THREAD

**Issue by stefaj** [frozenlib/lgbm-rs#4]
I see that categorical features supports a string as param, but I am unsure how to pass monotone_constraints as it requires a list of -1,0,1 specified for each feature. How would we go about setting it ?

If we take the example of  https://github.com/frozenlib/lgbm-rs/blob/4b64ee9c721a4543c239f5152d53f0f0d147ce9e/lgbm/tests/booster.rs#L86

Which type should this be (in the case of `monotone_constraints`), i64 ?

**Comment by frozenlib** [comment]
For `type = multi-int` parameters such as [`monotone_constraints`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#monotone_constraints), you can use `[i32]`,`[i64]`, `Vec<i32>` `Vec<i64>` `&'static str` as follows.

```
p.push("monotone_constraints", vec![0, 1]);
p.push("monotone_constraints", [0, 1i64]);
p.push("monotone_constraints", "0,1");
```

Parameters are converted to a string and passed to lightgbm, so the result is the same in all cases.

**Comment by stefaj** [comment]
Thank you ! Worked
